###
GET /v3/models HTTP/1.1
Host: 127.0.0.1:3006

###
GET /v3/models/6471c1135def4ba2b8564eaa HTTP/1.1
Host: 127.0.0.1:3006

###
GET /v3/models/64648adaf5294c788ca2369f HTTP/1.1
Host: 127.0.0.1:5005

###
POST /v3/models/ HTTP/1.1
Host: 127.0.0.1:5005
Content-Type: application/json

{
  "username": "Some9",
  "name": "Square",
  "modelType": "blend",
  "modelObj": {},
  "desc": "some model",
  "comments": ["Nice model", "Awesome Polygones"]
}
###
POST /v3/models?key=BIdAWH7i9n7YeC/kfM5MQ HTTP/1.1
Host: 127.0.0.1:5005
Content-Type: application/json

{
  "username": "Some9",
  "name": "Square",
  "modelType": "blend",
  "modelObj": {},
  "desc": "some model",
  "comments": ["Nice model", "Awesome Polygones"]
}

###
POST /v4/newUser HTTP/1.1
Host: 127.0.0.1:5005
Content-Type: application/json

{
  "username": "Jordan Carter"
}

###
PUT /v3/models/6471c1195def4ba2b8564eab?login=Mustfa&password=1111 HTTP/1.1
Host: 127.0.0.1:3006
Content-Type: application/json

{
  "username": "Mustafa",
  "name": "Cube",
  "modelType": "m3d",
  "modelObj": {},
  "desc": "some model",
  "comments": ["bad square", "Awesome Polygones"]
}

###
PUT /v3/models/6471c11a5def4ba2b8564eac?login=Mustafa&password=1111 HTTP/1.1
Host: 127.0.0.1:3006
Content-Type: application/json

{
  "username": "Mustafa",
  "name": "TestModel",
  "modelType": "m3d",
  "modelObj": {},
  "desc": "some model",
  "comments": ["Nice model", "Awesome Polygones", "It's so big"]
}


###
DELETE /v3/models/6471c11a5def4ba2b8564eac?login=Mstafa
Host: 127.0.0.1:5005
