swagger: "2.0"
info:
  title: This is documntation for my API
  description: SAPR express labs documentaion by Natur Mustafa 211-325
  version: 1.0
  servers:
    -url: "http://localhost:5005"
    description: This is my local server

paths:
  #Returns a Models list
  /v3/models:
    get:
      summary: Returns a list of models.
      description: Models witch are already registered
      responses:
        200: # status code
          description: Successul Response
          schema:
            type: object
            properties:
              id:
                type: integer
              name:
                type: string

  #Get Request with path id
  /v3/models/{ID}:
    get:
      summary: Returns a model by ID.
      description: Returns the Specific model
      parameters:
        - name: ID
          in: path
          required: true
          schema:
            type: integer
            format: int64
      responses:
        "200":
          description: OK
          schema:
            type: object
            example:
              {
                "_id": "#####################",
                "username": "#####",
                "name": "#####",
                "modelType": "#####",
                "modelObj": {},
                "desc": "#####",
                "comments": ["#####", "#####"],
                "creationDate": "#####",
                "lastChangesDate": "#####",
              }

  /v3/postModels:
    post:
      summary: Adds a new model
      produces:
        - application/json
      consumes:
        - application/json
      parameters:
        - in: query
          name: login
          type: string
          enum: ["Mustafa"]
          required: true

        - in: query
          name: password
          type: string
          enum: ["1111"]
          required: true

        - in: body
          name: body
          schema:
            properties:
              username:
                type: string
              name:
                type: string
              modelType:
                type: string
              modelObj:
                type: object
              desc:
                type: string
              comments:
                type: [string]
      responses:
        "200":
          description: OK

  /v3/newUser:
    post:
      summary: Adds a new user
      produces:
        - application/json
      consumes:
        - application/json
      parameters:
        - in: query
          name: newUserFlag
          type: string
          enum: ["true", "false"]
          required: true

        - in: body
          name: body
          schema:
            properties:
              username:
                type: string
      responses:
        "200":
          description: OK
