swagger: "2.0"
info:
  title: This is documntation for my API
  description: SAPR epress labs documentaion by Natur Mustafa 211-325
  version: 1.0
  servers:
    -url: "http://localhost:5005"
    description: This is my local server

paths:
  #Returns a Models list
  /v3/models:
    get:
      summary: Returns a list of models.
      description: Models witch are already registered
      responses:
        200: # status code
          description: Successul Response
          schema:
            type: object
            properties:
              id:
                type: integer
              name:
                type: string

  #Get Request with path id
  /v3/models/{ID}:
    get:
      summary: Returns a model by ID.
      description: Returns the Specific model
      parameters:
        - name: ID
          in: path
          required: true
          schema:
            type: integer
            format: int64
      responses:
        "200":
          description: OK
          schema:
            type: object
            example:
              {
                "_id": "#####################",
                "username": "#####",
                "name": "#####",
                "modelType": "#####",
                "modelObj": {},
                "desc": "#####",
                "comments": ["#####", "#####"],
                "creationDate": "#####",
                "lastChangesDate": "#####",
              }
